linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true 
    govet: true
    check-shadowing: true
    linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unused
    - deadcoderun:
  timeout: 5m
  issues-exit-code: 1
